services:
  - type: web
      name: healthconnect-backend
          plan: free
              env: node
                  rootDir: healthconnect-backend
                      buildCommand: npm install
                          startCommand: node server.js
                            - type: web
                                name: healthconnect-ml
                                    plan: free
                                        env: python
                                            rootDir: healthconnect-ml
                                                buildCommand: pip install -r requirements.txt
                                                    startCommand: gunicorn -b 0.0.0.0:$PORT app:app
